### ISSUE TITLE
sys.argv[1] returns no output / no mac address

### ISSUE THREAD

**Issue by ghost** [booboy/security_python_scripts#1]
running the script, I started getting nothing for the output of sys.argv command. Not sure how it was supposed to run, but I edited your code a bit with subprocess and it worked. Overall it is pretty useful.

**Comment by bpmcdevitt** [comment]
hey sanjar, is this for manufacturer_of_mac.py? the way i was running it was like this:

`(env) booboy@booboy.workstation[~/bin/mygit/security_python_scripts]: python2 manufacturer_of_mac.py 14:dd:a9:xx:xx:xx
ASUSTek COMPUTER INC.`
